services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Alpaka78
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/root/molecules_app
    depends_on:
      db:
        condition: service_healthy
