name: Docker Compose Action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}" >> $GITHUB_ENV

      - name: Run docker-compose
        run: |
          docker-compose up -d --build
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}

      - name: Wait for services to be ready
        run: sleep 30  

      - name: Execute tests in the running services
        run: |
          docker-compose exec -T app pytest

        run: sleep 30  

      - name: Execute tests in the running services
        run: |
          docker-compose exec -T app pytest
